workflows:
  # iOS WITHOUT code signing - for testing compilation
  ios-test:
    name: iOS Test Build (No Signing)
    max_build_duration: 60
    instance_type: mac_mini_m2
    
    environment:
      flutter: stable
      xcode: 15.4
      cocoapods: default
      
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $HOME/Library/Caches/CocoaPods
        
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
          
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod install --repo-update
          
      - name: Flutter build iOS (no codesign)
        script: |
          flutter build ios --release --no-codesign
            
    artifacts:
      - build/ios/iphoneos/*.app
      - /tmp/xcodebuild_logs/*.log
      
  # iOS WITH code signing - when you have Apple Developer account
  ios-release:
    name: iOS Release (With Signing)
    max_build_duration: 60
    instance_type: mac_mini_m2
    
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: com.hourlyugc.app
      flutter: stable
      xcode: latest
      cocoapods: default
      
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $HOME/Library/Caches/CocoaPods
        - ios/Pods
        
    scripts:
      - name: Set up code signing
        script: |
          xcode-project use-profiles
          
      - name: Get Flutter packages
        script: |
          flutter packages pub get
          
      - name: Install pods
        script: |
          cd ios && pod install
          
      - name: Flutter build iOS
        script: |
          flutter build ios --release --no-codesign
          
      - name: Build iOS IPA
        script: |
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme Runner
            
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      
    publishing:
      email:
        recipients:
          - your-email@example.com

  android-workflow:
    name: Android Workflow
    max_build_duration: 30
    instance_type: mac_mini_m2
    
    environment:
      flutter: stable
      java: 17
      
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $HOME/.gradle/caches
        
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
          
      - name: Build APK
        script: |
          flutter build apk --release
          
      - name: Build App Bundle
        script: |
          flutter build appbundle --release
          
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/bundle/**/*.aab
      
    publishing:
      email:
        recipients:
          - your-email@example.com
